### ISSUE TITLE
devfreq patch is broken

### ISSUE THREAD

**Issue by sergey-suloev** [mripard/sunxi-mali#12]
can't find file to patch at input line 22
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 9af33ab01cf84d90fe9a4d354b71dd304bca3010 Mon Sep 17 00:00:00 2001
|From: Maxime Ripard <maxime.ripard@free-electrons.com>
|Date: Thu, 30 Nov 2017 11:45:24 +0100
|Subject: [PATCH] mali: Make devfreq optional
|
|If the USING_DEVFREQ option is set, any device without operating points
|defined in the device tree will be treated as an hard error, making probe
|fail.
|
|Rework the driver a bit to ignore the property missing error, and treat all
|the others as hard errors.
|
|Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>
|---
| r6p2/src/devicedrv/mali/linux/mali_devfreq.c | 7 +++++--
| 1 file changed, 5 insertions(+), 2 deletions(-)
|
|diff --git a/r6p2/src/devicedrv/mali/linux/mali_devfreq.c b/r6p2/src/devicedrv/mali/linux/mali_devfreq.c
|index 0b0ba1481eed..c3a2636e6635 100755
|--- a/r6p2/src/devicedrv/mali/linux/mali_devfreq.c
|+++ b/r6p2/src/devicedrv/mali/linux/mali_devfreq.c
--------------------------
File to patch: 
Skip this patch?

**Comment by giuliobenetti** [comment]
@sergey-suloev 
Hi Sergey, just sent Pull Request to Maxime to fix this patch

**Comment by giuliobenetti** [comment]
Fix on new PR
