### ISSUE TITLE
Make memory-region mandatory

### ISSUE THREAD

**Issue by giuliobenetti** [mripard/sunxi-mali#20]
I've seen one of the main problem to get Mali working is that people forget to add <memory-region> in their dts.
I see that only pr_err is emitted if memory-region is not found with:
"Couldn't reserve our memory region. fbdev will not work"
But I simply don't know and ask, is there something else that could work?
I mean X11 for example.
Is this the meaning of not treating that as a hard error?

**Comment by mripard** [comment]
fbdev is the only reason why you'd need it, really.
X11 will work just fine without it, as any non decades old technology that will use KMS, as anyone should.

So no, we're not going to do that.
