### ISSUE TITLE
Compilation issue with linux-sunxi/sunxi-next

### ISSUE THREAD

**Issue by sergey-suloev** [mripard/sunxi-mali#28]
Hi guys
what patch do I need ?

/home/sergey/Projects/orpaltech/drivers/sunxi/sunxi-mali/r6p2/src/devicedrv/mali/platform/sunxi/sunxi.c: In function ‘mali_platform_device_register’:
/home/sergey/Projects/orpaltech/drivers/sunxi/sunxi-mali/r6p2/src/devicedrv/mali/platform/sunxi/sunxi.c:216:24: error: ‘struct device’ has no member named ‘cma_area’; did you mean ‘dma_parms’?
   struct cma *cma = dev->cma_area;

It seems like the branch is missing some important patch regarding CMA because the kernel's .config file has CONFIG_CMA disabled even after I manually provide it with value "y". As as result CONFIG_DMA_CMA is also missing and dev->cma_area member is not compiled along with device structure. 

Thanks

**Comment by giuliobenetti** [comment]
Hi @sergey-suloev, you have to use Linux from Torvalds, not sunxi-next.
I've suggested you wrong time ago.
Sunxi-next is a sort of hub to receive sunxi specific patches only.
So not to be used to start a project.
Sorry I've addressed you to the wrong path time ago.

**Comment by sergey-suloev** [comment]
ok thanks

**Comment by sergey-suloev** [comment]
@giuliobenetti  I actually always using mainline tree but this time I tried to switch to linux-sunxi as I thought linux-sunxi is the best option for sunxi devices ))
