### ISSUE TITLE
Problem with 4.17

### ISSUE THREAD

**Issue by sergey-suloev** [mripard/sunxi-mali#39]
Hello guys 

I can see the following boot log  with v4.17-rc1

[    7.102212] mali: loading out-of-tree module taints kernel.
[    7.114803] Allwinner sunXi mali glue initialized
[    7.296953] Mali: ERR: /home/sergey/Projects/orpaltech/drivers/sunxi/sunxi-mali/r6p2/src/devicedrv/mali/common/mali_pp.c
[    7.307913]            mali_pp_reset_wait() 269
                          
[    7.307926] Mali PP: Failed to reset core Mali_PP0, rawstat: 0x00000000

[    7.321612] Mali: ERR: /home/sergey/Projects/orpaltech/drivers/sunxi/sunxi-mali/r6p2/src/devicedrv/mali/common/mali_kernel_core.c
[    7.321618]            mali_parse_product_info() 174
                          
[    7.321620] Failed to create initial PP object

[    7.321698] Mali: ERR: /home/sergey/Projects/orpaltech/drivers/sunxi/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_kernel_linux.c
[    7.321702]            mali_probe() 606
                          
[    7.321704] mali_probe(): Failed to initialize Mali device driver.

[    7.321746] mali-utgard: probe of mali-utgard.0 failed with error -14
[    7.321855] Mali: 
[    7.321859] Mali device driver loaded

The error is coming from here https://github.com/mripard/sunxi-mali/blob/a5b9f18a165fb3c5d2bc4a0219a0c626bc72450e/r6p2/src/devicedrv/mali/common/mali_pp.c#L268  and is somehow related to hardware reset.

Any ideas ? It worked well with 4.16.

**Comment by mripard** [comment]
As usual, without a commit ID, SoC, board and config file, we can't help you.

**Comment by sergey-suloev** [comment]
Thanks, it has been resolved.

**Comment by Halolo** [comment]
Resolved by 4.17-rc2 or something else you did?

**Comment by sergey-suloev** [comment]
@Halolo I don't know. I was making many builds that evening and after 3-4 builds it was resolved with rc1. There might additional commits happen during that time period.

**Comment by timdorohin** [comment]
Same issue with 4.17.4 kernel on Orange Pi Lite running bionic nightly build.
Even the error codes are same.
What info i must provide?
[config-4.17.4-sunxi.txt](https://github.com/mripard/sunxi-mali/files/2170843/config-4.17.4-sunxi.txt)
[dmesg.txt](https://github.com/mripard/sunxi-mali/files/2170845/dmesg.txt)

P.S. Downgraded to 4.17.2 - same error.
