### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by sergey-suloev** [mripard/sunxi-mali#4]
Hi, 
in readme file did you mean  "DRM_FBDEV_OVERALLOC" option , which is 100 by default ?

Can you say a couple of words how to proceed with "The first thing needed would be to add a reserved memory region, shared by the Display Engine and the Mali GPU nodes." 
Should this be done via device tree? Can you put an example, please?

I found the following doc
https://www.kernel.org/doc/Documentation/devicetree/bindings/reserved-memory/reserved-memory.txt
Are you meaning this ?

Thanks

**Comment by mripard** [comment]
Both points should be fixed now.
