### ISSUE TITLE
ARMSOC(0): ERROR: Cannot allocate scanout buffer

### ISSUE THREAD

**Issue by hexdump0815** [mripard/sunxi-mali#63]
hello,

i have built and installed all according to the documentation, i.e.

* sunxi-mali .ko r6p2 (mripard) - loads fine and without errors
* xf86-video-armsoc (mripard)
* mali-blobs r6p2 arm x11_dma_buf (free-electrons)
* CONFIG_DMA_CMA=y CONFIG_CMA=y
* sun4i-drm display-engine: bound 1c16000.hdmi (ops sun4i_hdmi_driver_exit [sun4i_drm_hdmi])
* [drm] Initialized sun4i-drm 1.0.0 20150629 for display-engine on minor 0
* /dev/mali /dev/dri/card0 /dev/fb0 are all there and have the right permissions (via udev rule)
* kernel cmdline: ... cma=256M drm_kms_helper.drm_fbdev_overalloc=200 mali.mali_debug_level=5 sunxi_ve_mem_reserve=0 sunxi_g2d_mem_reserve=0 sunxi_fb_mem_reserve=16
* socs: bananapi m1 (a20) - kernel 4.19.17 and orangepi 2 plus (h3) - kernel 4.19.10 - both mali400mp2 and the gpu node is in the dts/dtb
* system ubuntu 18.04 armhf, lightdm, without mali and armsoc all is working fine

with this setup i get the following when starting x:

[  6019.669] (EE) _CREATE_GEM({height: 1024, width: 1280, bpp: 32 buf_type: 0x0}) failed. errno: 22 - Invalid argument
[  6019.669] (EE) ARMSOC(0): ERROR: Cannot allocate scanout buffer

on both systems, the bananapi and the orangepi - so something i seem to be doing wrong. any idea what the problem might be? i have sucessfully got mali running on an amlogic s905w soc using the meson mali driver, which seems to have a very similar setup - so a basic understanding of how the setup should be done should be there :)

a lot of thanks in advance and best wishes - hexdump

p.s.: i read through all the other issues around here which might be relevant and did not find anything else to try beyond what i have included already - the only thing which i'm not sure about is that hand picked commit from the NextThingCo repo, which does not exist anymore, but i guess that this is already in the patches here - right?

**Comment by rubitwa** [comment]
@hexdump0815 
https://github.com/armbian/build/blob/master/patch/kernel/sunxi-next/0005-drm-gem-cma-Export-with-handle-allocator.patch
https://github.com/armbian/build/blob/master/patch/kernel/sunxi-next/0006-drm-sun4i-Add-GEM-allocator.patch

**Comment by hexdump0815** [comment]
@rubitwa - cool - thanks a lot!

**Comment by hexdump0815** [comment]
the above patches fixed the problem ... sadly the performance on a bananpi is so low, especially the normal 2d performance due to the armsoc server, that it is not really worth it: on a bananapi m1 glmark2 gives a score of about 16 compared to 12 for pure software rendering (that with higher cpu usage though)
