### ISSUE TITLE
mali_memory.c:186:11: error: initialization from incompatible pointer type

### ISSUE THREAD

**Issue by iamdrq** [mripard/sunxi-mali#68]
sunxi-mali/r8p1/src/devicedrv/mali/linux/mali_memory.c:186:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .fault = mali_mem_vma_fault,
           ^~~~~~~~~~~~~~~~~~
sunxi-mali/r8p1/src/devicedrv/mali/linux/mali_memory.c:186:11: note: (near initialization for ‘mali_kernel_vm_ops.fault’)

sunxi-mali# uname -r
4.15.0-46-generic

when I run:
./build.sh -r r8p1 -u

but I got error,what is wrong?

**Comment by mripard** [comment]
It sohuld be fixed now, sorry for the trouble
