### ISSUE TITLE
Add sun50i-a64-mali in the compatible strings

### ISSUE THREAD

**Issue by bhush9** [mripard/sunxi-mali#73]
Currently `patches/0005-mali-Add-sunxi-platform.patch` doesn't list a64-mali identifier, which is "workarounded" in dtb by for example renaming the mali node as sun50i-h5-mali. It would be nice to get this fixed in sunxi-mali side.

**Comment by HonJEK** [comment]
I added a pull-request for it
https://github.com/mripard/sunxi-mali/pull/69/commits/612d839fd1cfe98e1049d6a1595eb4f1035c3907

**Comment by bgklc** [comment]
@HonJEK Could you please fix your SoB string so that @mripard could merge the pull-request https://github.com/mripard/sunxi-mali/pull/75 ? I use pine64 and use this as well, and need to apply this manually.

**Comment by HonJEK** [comment]
@vicseq @mripard pard Done

**Comment by bgklc** [comment]
@HonJEK thanks! Besides, can you insmod it under kernel 5.2? I use fedora, it is built and loaded successfully under 5.1, but not under 5.2 it builds, but fails to load.

**Comment by HonJEK** [comment]
No I have not tested it, because Mali is currently not needed by me and in the past I did not get the user library to work with SoPine board.

**Comment by sergey-suloev** [comment]
@vicseq  @HonJEK  hi, guys, I'm just curios: why are you still using this driver ?
LIMA has already been merged into the stable kernel, and you can now build MESA from sources too.

**Comment by HonJEK** [comment]
Because I didn't noticed it and the pull-request is from may. :-)
