### ISSUE TITLE
Building issue 

### ISSUE THREAD

**Issue by OOKAMIFR** [mripard/sunxi-mali#80]
Hello

I would like to build from a fresh stretch install mali drivers
the os i use is dietpi

cpu is H3 and gpu MALI 400MP2

my request is to know how to compile drivers from the begining
i tried to follow instruction but i have an error

root@DietPi:~# cd sunxi-mali
root@DietPi:~/sunxi-mali# export CROSS_COMPILE=$TOOLCHAIN_PREFIX
root@DietPi:~/sunxi-mali# export KDIR=$KERNEL_BUILD_DIR
root@DietPi:~/sunxi-mali# export INSTALL_MOD_PATH=$TARGET_DIR
root@DietPi:~/sunxi-mali# ./build.sh -r r6p2 -b
building...
~/sunxi-mali/r6p2 ~/sunxi-mali
./build.sh: line 15: quilt: command not found
Error applying patch
root@DietPi:~/sunxi-mali#

thanks for the help :)
.

**Comment by mripard** [comment]
You need to install quilt :)
