### ISSUE TITLE
Build mali on sunxi-next

### ISSUE THREAD

**Issue by avafinger** [mripard/sunxi-mali#81]
Hi @mripard 

I have tried to compile r6p2 on 5.5.0-rc5-next-20200109+ , but got this

```
sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_low_level_mem.c: In function ‘_mali_osk_mem_mapioregion’:
/arm/ubuntu/nanopi-a64-linux-next/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_low_level_mem.c:36:26: error: implicit declaration of function ‘ioremap_nocache’; did you mean ‘ioremap_cache’? [-Werror=implicit-function-declaration]
  return (mali_io_address)ioremap_nocache(phys, size);
                          ^~~~~~~~~~~~~~~
                          ioremap_cache
/arm/ubuntu/nanopi-a64-linux-next/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_low_level_mem.c:36:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  return (mali_io_address)ioremap_nocache(phys, size);
         ^

```
There is no ioremap_nocache on linux-next, what would be the equivalent function? How would be the workaround?

BR
@lex

**Comment by giuliobenetti** [comment]
Hi @avafinger,

I've tried to rebuild against torvalds/master branch and it has no problem at all.
sunxi-next branch is not stable, it's only a branch where sunxi-specific patches are committed before
being pulled from upstream(torvalds). So don't use sunxi-next branch, but at least a torvalds/master
or a stable/version from greghk(better a tag).

Best regards

**Comment by avafinger** [comment]
> I've tried to rebuild against torvalds/master branch and it has no problem at all.

Yes, there you have **ioremap_nocache**. I thought linux-next would become the next rc. There i have codec analog fully working on my board.

Anyway, thanks for the info.
