### ISSUE TITLE
Module signature/key missing

### ISSUE THREAD

**Issue by AnhDQHE181109** [mripard/sunxi-mali#86]
I was trying to load the _mali.ko_ module into the system. But whenever I try to load it, **dmesg** says: `mali: module verification failed: signature and/or required key missing - tainting kernel`

From what I've found on Google, this is caused by the module not having a proper signature built-in. The module version I was attempting with is _r9p0_ (the same still applies to _r6p2_) The architecture I built the module for is **aarch64**, the kernel version is **5.4.43-sunxi64**, **Mali 450 GPU** and Debian Buster.

So I'm wondering what I can do to resolve this? 
Do I need to disable the module signature checker feature in the kernel source and rebuild it? Or I just need to generate a signature for the module?

Any help would be much appreciated!!

**Comment by mripard** [comment]
There's not much to resolve, it's kind of working as expected (and your Google search is right). It's not really a big deal anyway, since the kernel is going to be tainted no matter what, since the module is an out-of-tree module.
