### ISSUE TITLE
Blank screen with Mali fbdev on Cubieboard2 A20 kernel >= 4.20 and solution

### ISSUE THREAD

**Issue by hor63** [mripard/sunxi-mali#90]
When I run test.c on a Cubieboard with A20 under Kernel 5.10.48 with OOTB dtb for Cubieboard2 the screen remains black.
I followed all your instructions to enable physical address leaking, and the test program produces all EGL and OpenGL ES 2.0 information properly.
I can also switch back to console by switching to another console and back with ALT-F2 and ALT-F1.
But Mali does not render the image.

Solution: Add the parameter "cma=256M" to boot.cmd to the the kernel boot arguments like this:

`setenv bootargs console=tty0 root=/dev/mmcblk0p2 rootwait consoleblank=0 panic=10 drm_kms_helper.drm_leak_fbdev_smem=1 cma=256M`

You may want to add this hint to you readme.
Thanks.

**Comment by giuliobenetti** [comment]
@hor63 thanks a lot for pointing, I've just opened #91 for this.

**Comment by hor63** [comment]
Solved by y #91
